name: XDRVpp CI

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ARM GCC toolchain
        run: |
          sudo apt-get update
          sudo apt install gcc-arm-none-eabi binutils-arm-none-eabi

      - name: Build
        run: |
          make


