name: XDRVpp CI

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mustafaerrgun/xdrv-builder:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        run: make
